"""add content_hash to materials

Revision ID: c8147273d321
Revises: d940f93ecf70
Create Date: 2026-10-04 16:45:18.902704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8147273d321'
down_revision: Union[str, Sequence[str], None] = 'd940f93ecf70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_materials_content_hash'), 'materials', ['content_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_materials_content_hash'), table_name='materials')
    op.drop_column('materials', 'content_hash')
    # ### end Alembic commands ###
